"""costs_acceptances

Revision ID: b909842f69b4
Revises: b7d2c9a4e1f8
Create Date: 2026-07-17 10:33:50.577461
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b909842f69b4"
down_revision: str | None = "b7d2c9a4e1f8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Create the new tables with plain text columns so the migration is
    # compatible with the existing PostgreSQL database state.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "acceptance",
        sa.Column("project_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("inspector", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("client_rep", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_acceptance_project_code"), "acceptance", ["project_code"], unique=False
    )
    op.create_table(
        "cost",
        sa.Column("project_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("is_incident", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cost_project_code"), "cost", ["project_code"], unique=False
    )
    op.alter_column(
        "project",
        "type",
        existing_type=sa.VARCHAR(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "project",
        "stage",
        existing_type=sa.VARCHAR(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "project",
        "schedule_outcome",
        existing_type=sa.VARCHAR(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "project",
        "contract_value",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(),
        existing_nullable=False,
    )
    op.alter_column(
        "project",
        "estimated_cost",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project",
        "estimated_cost",
        existing_type=sa.Numeric(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "project",
        "contract_value",
        existing_type=sa.Numeric(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "project",
        "schedule_outcome",
        existing_type=sa.Enum("ON_TIME", "DELAYED", "EARLY", name="scheduleoutcome"),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "project",
        "stage",
        existing_type=sa.Enum(
            "YEU_CAU",
            "KHAO_SAT",
            "BAO_GIA",
            "HOP_DONG",
            "CHUAN_BI",
            "THI_CONG",
            "NGHIEM_THU",
            "QUYET_TOAN",
            "THANH_TOAN",
            "DONG",
            name="projectstage",
        ),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "project",
        "type",
        existing_type=sa.VARCHAR(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_cost_project_code"), table_name="cost")
    op.drop_table("cost")
    op.drop_index(op.f("ix_acceptance_project_code"), table_name="acceptance")
    op.drop_table("acceptance")
    # ### end Alembic commands ###
