/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    projects: Project;
    testimonials: Testimonial;
    'contact-submissions': ContactSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'vi' | 'vi'[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'vi';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Admins manage users, site settings, and deletions; editors manage content.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Stable id consumed by the web app (e.g. "cleaning_deep").
   */
  slug: string;
  title: string;
  description: string;
  category: 'cleaning' | 'construction';
  duration: string;
  benefits: {
    item: string;
    id?: string | null;
  }[];
  features: {
    item: string;
    id?: string | null;
  }[];
  /**
   * lucide-react icon name, e.g. "Sparkles".
   */
  iconName: string;
  popular?: boolean | null;
  /**
   * Display order (ascending).
   */
  order?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * Stable id consumed by the web app (e.g. "proj_hig_coffee").
   */
  slug: string;
  title: string;
  client: string;
  category: 'cleaning' | 'construction';
  location: string;
  area: string;
  completionTime: string;
  description: string;
  achievement: string;
  /**
   * Upload the project cover photo. Fills the image URL below automatically.
   */
  image?: (number | null) | Media;
  /**
   * Auto-filled from the uploaded image above, or paste an external image URL.
   */
  imageUrl: string;
  tags: {
    item: string;
    id?: string | null;
  }[];
  /**
   * Optional client quote for this project. Leave author blank to omit.
   */
  testimonial?: {
    author?: string | null;
    role?: string | null;
    content?: string | null;
    /**
     * Upload the author photo. Fills the avatar URL below automatically.
     */
    avatar?: (number | null) | Media;
    /**
     * Auto-filled from the uploaded avatar above, or paste an external URL.
     */
    avatarUrl?: string | null;
    rating?: number | null;
  };
  /**
   * Display order (ascending).
   */
  order?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Stable id consumed by the web app (e.g. "testi_1").
   */
  slug: string;
  author: string;
  role: string;
  company: string;
  content: string;
  rating: number;
  /**
   * Upload the author photo. Fills the avatar URL below automatically.
   */
  avatar?: (number | null) | Media;
  /**
   * Auto-filled from the uploaded avatar above, or paste an external URL.
   */
  avatarUrl: string;
  category: 'cleaning' | 'construction' | 'both';
  /**
   * Display order (ascending).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  fullName: string;
  email?: string | null;
  phone: string;
  serviceCategory: 'cleaning' | 'construction' | 'both';
  /**
   * Slug of the requested service (matches a Services.slug). Blank = no specific package.
   */
  serviceId?: string | null;
  companyName?: string | null;
  address?: string | null;
  message?: string | null;
  status: 'new' | 'processing' | 'contacted';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  description?: T;
  category?: T;
  duration?: T;
  benefits?:
    | T
    | {
        item?: T;
        id?: T;
      };
  features?:
    | T
    | {
        item?: T;
        id?: T;
      };
  iconName?: T;
  popular?: T;
  order?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  client?: T;
  category?: T;
  location?: T;
  area?: T;
  completionTime?: T;
  description?: T;
  achievement?: T;
  image?: T;
  imageUrl?: T;
  tags?:
    | T
    | {
        item?: T;
        id?: T;
      };
  testimonial?:
    | T
    | {
        author?: T;
        role?: T;
        content?: T;
        avatar?: T;
        avatarUrl?: T;
        rating?: T;
      };
  order?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  slug?: T;
  author?: T;
  role?: T;
  company?: T;
  content?: T;
  rating?: T;
  avatar?: T;
  avatarUrl?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  phone?: T;
  serviceCategory?: T;
  serviceId?: T;
  companyName?: T;
  address?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  company?: {
    /**
     * Full legal company name.
     */
    name?: string | null;
    shortName?: string | null;
    /**
     * Year founded, e.g. "2019".
     */
    founded?: string | null;
    /**
     * Primary contact number — the main call-to-action channel.
     */
    phone?: string | null;
    email?: string | null;
    /**
     * Head office address.
     */
    address?: string | null;
    /**
     * Secondary branch address.
     */
    branch?: string | null;
    motto?: string | null;
    certification?: string | null;
  };
  /**
   * Optional social / messaging links — rendered as icons in the footer when set.
   */
  social?: {
    facebook?: string | null;
    zalo?: string | null;
    messenger?: string | null;
  };
  /**
   * Wordmark text and short taglines shown in the header and footer.
   */
  branding?: {
    /**
     * First half of the wordmark, e.g. "Green".
     */
    logoTextPrimary?: string | null;
    /**
     * Second half of the wordmark, e.g. "Orange".
     */
    logoTextSecondary?: string | null;
    /**
     * Small line under the logo in the header.
     */
    headerTagline?: string | null;
    /**
     * Small line under the logo in the footer.
     */
    footerTagline?: string | null;
  };
  /**
   * Primary navigation links and header CTAs.
   */
  navigation?: {
    /**
     * Links shown in the desktop nav and mobile drawer.
     */
    items?:
      | {
          label: string;
          /**
           * Page section this link scrolls to.
           */
          sectionId: 'hero' | 'introduction' | 'services' | 'projects' | 'testimonials' | 'contact';
          id?: string | null;
        }[]
      | null;
    /**
     * Desktop header button label.
     */
    headerCtaLabel?: string | null;
    /**
     * Mobile drawer button label (typically longer).
     */
    mobileCtaLabel?: string | null;
  };
  /**
   * Landing hero section copy, headline, CTAs, and benefits.
   */
  hero?: {
    /**
     * Full-bleed background photo behind the hero card. Leave empty to fall back to the default Unsplash photo.
     */
    backgroundImage?: (number | null) | Media;
    /**
     * Pill label above the headline (e.g. "Tiêu chuẩn quốc tế ISO 9001:2015 ...").
     */
    trustBadge?: string | null;
    /**
     * The decorated multi-line headline, broken into colored pieces. The renderer will join segments with a space and respect "new line before".
     */
    headlineSegments?:
      | {
          text: string;
          color: 'white' | 'emerald' | 'orange';
          /**
           * Render this segment in italic.
           */
          italic?: boolean | null;
          /**
           * Start a new line before this segment.
           */
          newLineBefore?: boolean | null;
          id?: string | null;
        }[]
      | null;
    /**
     * The paragraph under the main hero heading.
     */
    subheadline?: string | null;
    /**
     * Selling points shown in the 2x2 grid inside the hero card.
     */
    benefits?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Filled orange button.
     */
    primaryCta?: {
      label?: string | null;
      /**
       * Anchor like "#contact" or an external URL.
       */
      href?: string | null;
    };
    /**
     * Outline button next to the primary CTA.
     */
    secondaryCta?: {
      label?: string | null;
      href?: string | null;
    };
    /**
     * Mini line below the CTAs (e.g. "Cam kết đồng hành tin cậy...").
     */
    trustStrap?: string | null;
  };
  /**
   * Headline counters (e.g. "500+" projects delivered).
   */
  stats?:
    | {
        /**
         * e.g. "500+"
         */
        value: string;
        label: string;
        /**
         * Tailwind text-color class, e.g. "text-green-600".
         */
        color?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Company introduction section: brand story, brand-color meanings, and the 5-step process.
   */
  introduction?: {
    /**
     * Small label above the heading.
     */
    eyebrow?: string | null;
    heading?: string | null;
    /**
     * Long company-narrative paragraph. Use **text** for bold; the placeholder {founded} expands to the founding year from Company tab.
     */
    narrative?: string | null;
    /**
     * Square photo shown next to the brand-color story.
     */
    image?: (number | null) | Media;
    /**
     * Label above the motto overlay on the photo (e.g. "Phương châm làm nghề").
     */
    mottoEyebrow?: string | null;
    /**
     * Heading next to the photo.
     */
    brandStoryHeading?: string | null;
    /**
     * Paragraph under the brand-story heading.
     */
    brandStoryIntro?: string | null;
    /**
     * The three brand colors and the meaning each represents. Recommend exactly 3 entries.
     */
    brandValues?:
      | {
          title: string;
          description: string;
          icon: 'Wrench' | 'ShieldCheck' | 'Trees';
          accent: 'orange' | 'slate' | 'emerald';
          id?: string | null;
        }[]
      | null;
    /**
     * Label above the process heading (e.g. "Khép kín & Hoàn hảo").
     */
    processEyebrow?: string | null;
    processHeading?: string | null;
    processIntro?: string | null;
    /**
     * Service-delivery process steps. Recommend exactly 5 entries.
     */
    processSteps?:
      | {
          /**
           * Two-digit string e.g. "01".
           */
          num: string;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Footer copy, column headings, and quick links.
   */
  footer?: {
    /**
     * Short paragraph under the footer logo.
     */
    brandDescription?: string | null;
    /**
     * Heading above the quick-links column.
     */
    quickLinksHeading?: string | null;
    /**
     * Anchor links listed in the quick-links column.
     */
    quickLinks?:
      | {
          label: string;
          sectionId: 'hero' | 'introduction' | 'services' | 'projects' | 'testimonials' | 'contact';
          id?: string | null;
        }[]
      | null;
    /**
     * Heading above the addresses column.
     */
    officesHeading?: string | null;
    /**
     * Label above the head-office address (e.g. "Trụ Sở Hà Nội:").
     */
    headquartersLabel?: string | null;
    /**
     * Label above the branch address.
     */
    branchLabel?: string | null;
    /**
     * Heading above the phone/email column.
     */
    supportHeading?: string | null;
    /**
     * Text shown before the phone number (e.g. "Hotline:").
     */
    hotlinePrefix?: string | null;
    /**
     * Text shown before the email address (e.g. "Email:").
     */
    emailPrefix?: string | null;
    /**
     * Text after "© YEAR Company Name." in the footer base.
     */
    copyrightSuffix?: string | null;
    /**
     * Label on the back-to-top link in the footer base.
     */
    backToTopLabel?: string | null;
  };
  /**
   * Default metadata used when a page has no specific SEO entry.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Social share image (Open Graph / Twitter card).
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  company?:
    | T
    | {
        name?: T;
        shortName?: T;
        founded?: T;
        phone?: T;
        email?: T;
        address?: T;
        branch?: T;
        motto?: T;
        certification?: T;
      };
  social?:
    | T
    | {
        facebook?: T;
        zalo?: T;
        messenger?: T;
      };
  branding?:
    | T
    | {
        logoTextPrimary?: T;
        logoTextSecondary?: T;
        headerTagline?: T;
        footerTagline?: T;
      };
  navigation?:
    | T
    | {
        items?:
          | T
          | {
              label?: T;
              sectionId?: T;
              id?: T;
            };
        headerCtaLabel?: T;
        mobileCtaLabel?: T;
      };
  hero?:
    | T
    | {
        backgroundImage?: T;
        trustBadge?: T;
        headlineSegments?:
          | T
          | {
              text?: T;
              color?: T;
              italic?: T;
              newLineBefore?: T;
              id?: T;
            };
        subheadline?: T;
        benefits?:
          | T
          | {
              item?: T;
              id?: T;
            };
        primaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        trustStrap?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        color?: T;
        id?: T;
      };
  introduction?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        narrative?: T;
        image?: T;
        mottoEyebrow?: T;
        brandStoryHeading?: T;
        brandStoryIntro?: T;
        brandValues?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              accent?: T;
              id?: T;
            };
        processEyebrow?: T;
        processHeading?: T;
        processIntro?: T;
        processSteps?:
          | T
          | {
              num?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  footer?:
    | T
    | {
        brandDescription?: T;
        quickLinksHeading?: T;
        quickLinks?:
          | T
          | {
              label?: T;
              sectionId?: T;
              id?: T;
            };
        officesHeading?: T;
        headquartersLabel?: T;
        branchLabel?: T;
        supportHeading?: T;
        hotlinePrefix?: T;
        emailPrefix?: T;
        copyrightSuffix?: T;
        backToTopLabel?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}